model:
  base_learning_rate: 0.0001
  lr_schedule:
    type: cosine
    max_steps: 200000
    warmup_steps: 10000
    min_lr_scale: 0.01
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 8
    n_embed: 8192
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 8
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 32
    train:
      target: taming.data.base.ImageDataset
      params:
        size:
        - 512
        - 512
        root_dir: ./data/ffhq/images1024x1024
        file_list: ./data/ffhq/train_image.txt
    validation:
      target: taming.data.base.ImageDataset
      params:
        size:
        - 512
        - 512
        root_dir: ./data/ffhq/images1024x1024
        file_list: ./data/ffhq/val_image.txt
